#!/bin/bash
# Contract tests for hooks/session-knowledge.sh — SessionStart injects additionalContext
# when the knowledge base has entries; silent exit 0 when empty or missing.
source "$(dirname "$0")/../lib.sh"

H=session-knowledge.sh

# Helpers -------------------------------------------------------------------

# Create a fixture docs/solutions dir inside a repo with a given INDEX content
make_kb() {
    local repo="$1" index_content="$2" critical_content="${3:-}"
    mkdir -p "$repo/docs/solutions"
    printf '%s\n' "$index_content" > "$repo/docs/solutions/INDEX.md"
    if [ -n "$critical_content" ]; then
        printf '%s\n' "$critical_content" > "$repo/docs/solutions/critical-patterns.md"
    fi
}

# make_active_run <root> <slug> <state> — writes a minimal RUN.json fixture directly (no
# need to run runtime/run_state.py init for these hook-level tests).
make_active_run() {
    local root="$1" slug="$2" state="$3"
    mkdir -p "$root/specs/$slug"
    cat > "$root/specs/$slug/RUN.json" <<JSON
{"slug": "$slug", "run_id": "r1", "state": "$state", "seq": 1,
 "waiting_on": null, "resume_event": null, "sha": null,
 "created_at": "2026-01-01T00:00:00Z", "updated_at": "2026-01-01T00:00:00Z",
 "last_event_id": "e1"}
JSON
}

# Minimal populated INDEX with one real entry row
_REAL_INDEX='# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.
> Last updated: 2026-06-11 | 1 total entries

## some-category
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| [my-entry](some-category/my-entry.md) | knowledge | standard | foo, bar | Use when doing something |'

# Empty formats ---------------------------------------------------------------

t "bootstrap empty format (placeholder row) → silent exit 0"
repo=$(new_repo $H)
make_kb "$repo" '# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.

## Entries
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| _(empty — no solutions recorded yet)_ | | | | |'
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "rebuild empty format (0 entries header, no data rows) → silent exit 0"
repo=$(new_repo $H)
make_kb "$repo" '# Knowledge Base Index
> Auto-generated by /compound — do not edit manually.
> Last updated: 2026-06-11 | 0 total entries'
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "INDEX.md missing → silent exit 0"
repo=$(new_repo $H)
# No docs/solutions dir at all
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
assert_silent_ok

t "has entries → valid JSON output (jq parseable)"
repo=$(new_repo $H)
make_kb "$repo" "$_REAL_INDEX" "# Critical Patterns

## Entry 1
Some content here."
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ "$RC" -ne 0 ]; then
    fail "rc=$RC (want 0) — out: $OUT"
elif [ -z "$OUT" ]; then
    fail "expected JSON output, got empty stdout"
elif ! printf '%s' "$OUT" | jq -e . >/dev/null 2>&1; then
    fail "output is not valid JSON — out: $(echo "$OUT" | head -3)"
else
    pass
fi

t "has entries → additionalContext contains entry name from fixture"
repo=$(new_repo $H)
make_kb "$repo" "$_REAL_INDEX" "# Critical Patterns"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if echo "$OUT" | grep -q "my-entry"; then pass
else fail "expected 'my-entry' in output — out: $(echo "$OUT" | head -3)"; fi

t "INDEX longer than 30 lines → truncated at threshold (31st line content absent)"
repo=$(new_repo $H)
# Build INDEX where line 31 has a distinctive marker
_long_index='# Knowledge Base Index
> Last updated: 2026-06-11 | 1 total entries

## cat
| File | Type | Severity | Tags | Applicable When |
|---|---|---|---|---|
| [entry-a](cat/entry-a.md) | knowledge | standard | a | When A |
line8
line9
line10
line11
line12
line13
line14
line15
line16
line17
line18
line19
line20
line21
line22
line23
line24
line25
line26
line27
line28
line29
line30
SHOULD_BE_TRUNCATED_LINE_31
line32'
make_kb "$repo" "$_long_index"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ -z "$OUT" ]; then
    fail "expected JSON output but got empty stdout"
elif echo "$OUT" | grep -q "SHOULD_BE_TRUNCATED_LINE_31"; then
    fail "line 31 content leaked past the 30-line cap"
else
    pass
fi

t "critical-patterns.md > 40 lines → only heading lines (non-heading body line beyond cap absent)"
repo=$(new_repo $H)
# Build a critical-patterns.md with >40 lines including a distinctive non-heading body line
_cp_lines="# Critical Patterns
## Entry 1
short body"
# Pad to 42 lines total with a distinctive body line on line 42
for i in $(seq 4 41); do
    _cp_lines="$_cp_lines
padding line $i"
done
_cp_lines="$_cp_lines
BODY_LINE_BEYOND_CAP_42"

make_kb "$repo" "$_REAL_INDEX" "$_cp_lines"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions"
if [ -z "$OUT" ]; then
    fail "expected JSON output but got empty stdout"
elif echo "$OUT" | grep -q "BODY_LINE_BEYOND_CAP_42"; then
    fail "non-heading body line beyond 40-line cap leaked into output"
elif ! echo "$OUT" | grep -q "Critical Patterns"; then
    fail "expected heading '# Critical Patterns' in output"
else
    pass
fi

# DR-2 regression: the DEPLOYED copy runs from .claude/hooks/, so the repo-root resolver
# (not the SESSION_KNOWLEDGE_DIR override used above) must find docs/solutions at the project
# root. This is the exact path the old `$HOOK_DIR/..` got wrong and no test exercised.
t "DR-2: deployed .claude/hooks/ location loads KB without SESSION_KNOWLEDGE_DIR override"
drepo=$(mktemp -d); _CLEANUP_DIRS+=("$drepo")
git -C "$drepo" init -q 2>/dev/null
mkdir -p "$drepo/.claude/hooks" "$drepo/docs/solutions"
cp "$ROOT/hooks/$H" "$drepo/.claude/hooks/"
printf '%s\n' "$_REAL_INDEX" > "$drepo/docs/solutions/INDEX.md"
OUT=$(cd "$drepo" && printf '' | bash ".claude/hooks/$H" 2>&1); RC=$?
if [ "$RC" -eq 0 ] && printf '%s' "$OUT" | grep -q "my-entry"; then pass
else fail "deployed hook did not load KB from project root — rc=$RC out: $(echo "$OUT" | head -3)"; fi

# --- Active-run reporting (Phase C, GitHub issue #129) ---------------------------------

t "active run present, KB empty → JSON output with run slug, no crash"
repo=$(new_repo $H)
mkdir -p "$repo/docs/solutions" "$repo/runtime"
printf '%s\n' '# Knowledge Base Index
> Last updated: 2026-06-11 | 0 total entries' > "$repo/docs/solutions/INDEX.md"
cp "$ROOT/runtime/run_state.py" "$repo/runtime/"
make_active_run "$repo" "demo-slug" "implementing"
OUT=$(cd "$repo" && printf '' | RUN_STATE_REPO_ROOT="$repo" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions" bash "hooks/$H" 2>&1); RC=$?
if [ "$RC" -ne 0 ]; then fail "rc=$RC (want 0)"
elif ! printf '%s' "$OUT" | jq -e . >/dev/null 2>&1; then fail "output is not valid JSON"
elif ! echo "$OUT" | grep -q "demo-slug"; then fail "expected 'demo-slug' in output"
else pass; fi

t "no active runs, KB empty → silent exit 0"
repo=$(new_repo $H)
mkdir -p "$repo/docs/solutions" "$repo/runtime"
printf '%s\n' '# Knowledge Base Index
> Last updated: 2026-06-11 | 0 total entries' > "$repo/docs/solutions/INDEX.md"
cp "$ROOT/runtime/run_state.py" "$repo/runtime/"
run_hook "$repo" $H "" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions" RUN_STATE_REPO_ROOT="$repo"
assert_silent_ok

t "runtime/run_state.py absent (older harness install) → falls back to KB-only, no crash"
repo=$(new_repo $H)
make_kb "$repo" "$_REAL_INDEX" "# Critical Patterns"
OUT=$(cd "$repo" && printf '' | RUN_STATE_REPO_ROOT="$repo" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions" bash "hooks/$H" 2>&1); RC=$?
if [ "$RC" -eq 0 ] && echo "$OUT" | grep -q "my-entry"; then pass
else fail "expected KB-only output when run_state.py absent — rc=$RC out: $(echo "$OUT" | head -3)"; fi

t "more than 5 active runs → bounded to 5 in output"
repo=$(new_repo $H)
mkdir -p "$repo/docs/solutions" "$repo/runtime"
printf '%s\n' '# Knowledge Base Index
> Last updated: 2026-06-11 | 0 total entries' > "$repo/docs/solutions/INDEX.md"
cp "$ROOT/runtime/run_state.py" "$repo/runtime/"
for i in 1 2 3 4 5 6 7; do make_active_run "$repo" "slug-$i" "implementing"; done
OUT=$(cd "$repo" && printf '' | RUN_STATE_REPO_ROOT="$repo" SESSION_KNOWLEDGE_DIR="$repo/docs/solutions" bash "hooks/$H" 2>&1); RC=$?
_count=$(echo "$OUT" | grep -oE 'slug-[0-9]' | sort -u | wc -l | tr -d ' ')
if [ "$RC" -eq 0 ] && [ "$_count" -le 5 ]; then pass
else fail "expected <=5 distinct slugs in output, got $_count — out: $(echo "$OUT" | head -5)"; fi

finish
