#!/usr/bin/env python3
"""Deterministically rebuild docs/solutions/INDEX.md from solution frontmatter."""
from __future__ import annotations
import argparse
import re
import sys
from datetime import date
from pathlib import Path

FIELDS = ("problem_type", "severity", "tags", "applicable_when", "confirmed_at")

def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    data = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"').strip("'")
    return data

def build(root: Path) -> str:
    base = root / "docs/solutions"
    rows = []
    if base.is_dir():
        for path in sorted(base.rglob("*.md")):
            if path.name in {"INDEX.md", "critical-patterns.md"}:
                continue
            rel = path.relative_to(base)
            meta = frontmatter(path)
            rows.append((rel.parts[0] if len(rel.parts) > 1 else "—", rel, meta))
    rows.sort(key=lambda row: (row[0], row[2].get("confirmed_at", "")), reverse=False)
    grouped: dict[str, list[tuple[Path, dict[str, str]]]] = {}
    for category, rel, meta in rows:
        grouped.setdefault(category, []).append((rel, meta))
    out = ["# Knowledge Base Index", "> Auto-generated by the compound skill — do not edit manually.",
           f"> Last updated: {date.today().isoformat()} | {len(rows)} total entries", ""]
    for category in sorted(grouped):
        out += [f"## {category}", "| File | Type | Severity | Tags | Applicable When |", "|---|---|---|---|---|"]
        for rel, meta in sorted(grouped[category], key=lambda item: item[1].get("confirmed_at", ""), reverse=True):
            def val(key: str) -> str: return meta.get(key) or "—"
            tags = val("tags").strip("[]")
            out.append(f"| [{rel.stem}]({rel.as_posix()}) | {val('problem_type')} | {val('severity')} | {tags} | {val('applicable_when')} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"

def _default_root() -> Path:
    """Repo root. A deployed copy sits at <repo>/.claude/scripts/, one level in."""
    here = Path(__file__).resolve().parents[1]
    return here.parent if here.name == ".claude" else here


def main() -> int:
    p = argparse.ArgumentParser(); p.add_argument("--root", type=Path, default=_default_root()); p.add_argument("--check", action="store_true"); p.add_argument("--dry-run", action="store_true"); args=p.parse_args()
    output = build(args.root.resolve()); path=args.root.resolve()/"docs/solutions/INDEX.md"
    if args.check:
        if not path.is_file() or path.read_text(encoding="utf-8") != output:
            print("solution-index: INDEX.md is stale", file=sys.stderr); return 1
        print("solution-index: INDEX.md is current"); return 0
    if args.dry_run:
        print(output, end=""); return 0
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(output, encoding="utf-8"); print(f"solution-index: wrote {path}"); return 0
if __name__ == "__main__": raise SystemExit(main())
